import { 
  Geist, 
  Geist_Mono, 
  Poppins, 
  Inter, 
  Open_Sans, 
  Roboto,
  Nanum_Myeongjo,
  Tauri
} from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/footer";  
import Header from "./components/layout/header";


import ReduxProvider from "./components/ReduxProvider";
import ConsentLoader from "./components/ConsentLoader";
import AnalyticsLoader from "./components/AnalyticsLoader";
import CookieWrapper from "./components/CookieWrapper";

// 1. Poppins (Good for Headings & Hindi)
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "devanagari"],
  variable: "--font-poppins",
});

const nanum = Nanum_Myeongjo({
  weight: ["400", "700", "800"],
  subsets: ['latin'],
  variable: '--font-nanum', // CSS variable define karein
});
const tauri = Tauri({
  weight: '400', // Tauri mein sirf 400 weight hi hota hai
  subsets: ['latin'],
  variable: '--font-tauri',
});
// 2. Inter (Professional UI font)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// 3. Open Sans (Clean & highly readable)
const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

// 4. Roboto (Classic Android/Google style)
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Spreadext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable} 
        ${poppins.variable} 
        ${inter.variable} 
        ${openSans.variable} 
        ${roboto.variable} 
        ${tauri.variable}
        ${nanum.variable}
        h-full antialiased
      `}
    
    >
      <body className="min-h-full flex flex-col">
        {/* <Header />
        {children}
        <Footer /> */}
         {/* ✅ Redux Provider wrap */}
        <ReduxProvider>
          <ConsentLoader />
          <AnalyticsLoader />

          <Header />

          <CookieWrapper>
            {children}
          </CookieWrapper>

          <Footer />
        </ReduxProvider>
        </body>
    </html>
  );
}
